import os

from fastapi import APIRouter, HTTPException

from app.models.schemas import ChatRequest, ChatResponse

router = APIRouter()

DEV_MODE = os.getenv("DEV_MODE", "true").lower() == "true"


@router.post("/chat", response_model=ChatResponse)
async def chat(req: ChatRequest):
    """Handle conversational follow-up questions."""
    if DEV_MODE:
        from app.routers.match import _sessions

        session = _sessions.get(req.session_id)
        if not session:
            raise HTTPException(status_code=404, detail="Session not found")

        archetype = session["archetype_result"]["primary_archetype"]["name"]
        reply = (
            f"Great question! Based on your {archetype} archetype profile, "
            f"I can share that athletes with similar builds have historically "
            f"competed across a range of Team USA events. "
            f"In production, this response would be generated by Gemini with "
            f"live BigQuery data access. For now, the matching engine and "
            f"session management are fully operational."
        )

        session["messages"].append({"role": "user", "content": req.message})
        session["messages"].append({"role": "assistant", "content": reply})

        return ChatResponse(reply=reply)

    else:
        from app.services.gemini_agent import handle_chat_message
        from app.services.firestore_service import get_session, update_session_messages

        session = await get_session(req.session_id)
        if not session:
            raise HTTPException(status_code=404, detail="Session not found")

        reply = await handle_chat_message(
            session_id=req.session_id,
            message=req.message,
            session_context=session,
        )

        await update_session_messages(req.session_id, req.message, reply)

        return ChatResponse(reply=reply)
